### ISSUE TITLE
Spinner doesn't stop when transitioning to a page with Spinner set to disabled

### ISSUE THREAD

**Issue by cdcharlebois** [mendix/MobileFeatures#12]
When you've got two pages, such that the first page has this widget with Spinner enabled and the second page has this widget with Spinner disabled, the spinner is shown on the navigation between pages but not destroyed when the second page is shown.

**Comment by JelteMX** [comment]
If you read the description, you will see that it should be placed in a layout, not a page. So this is added once, not multiple times, and should be the same for the whole application. Adding the widget multiple times might produce undesirable behaviour.

If you have a test-project to reproduce this, let me know. I might be able to check if we need to fix something.
