### ISSUE TITLE
The spinner isn't always removed properly

### ISSUE THREAD

**Issue by KevinVlaanderen** [mendix/MobileFeatures#4]
Reproduction (using the Mendix Mobile app):
- Load a hybrid app with security enabled e.g. using the QR scanner
- Login in to the hybrid app
- Log out and directly do three-finger tap (the gesture to bring up the context menu)
- Sometimes, the spinner remains visible, blocking all input

**Comment by JelteMX** [comment]
Can you test [this version](https://github.com/mendix/MobileFeatures/raw/fix_ticket_54440_spinner_on_logout/dist/MobileFeatures.mpk)? This should fix the problem, but I haven't merged it into the widget yet

**Comment by KevinVlaanderen** [comment]
Thanks! It would be great if @simo101 could try this with one of the AoP apps on TEST. It's sometimes causing issues there, and that's faster than setting up a repro project.
